// Phase 7 Workstream B — pure-Dart loader tests for the 32 MMAH-format
// glyph JSONs at assets/tracing/.
//
// These tests verify:
//   1. assetPathFor(letter) returns the canonical asset path per slug.
//   2. parseGlyphJson(rawJson) returns a strongly-typed [TraceGlyph] with
//      character + non-empty strokes + non-empty medians + matching
//      stroke/median count + radStrokes (default to []).
//   3. validateMmah(rawJson) accepts every shipped glyph in
//      assets/tracing/ (32 files via the kIcelandicAlphabet enum).
//   4. Diacritic letters (á é í ó ú ý ö) have ≥2 strokes and the last
//      stroke's median bounding box sits ABOVE the previous stroke's
//      median bounding box (Pitfall §2 — accent-as-LAST convention).
//   5. ð and þ have exactly 2 strokes (body + bowl/cross-bar; D-04).
//
// The loader lives in `lib/core/tracing/glyph_loader.dart` — pure Dart,
// no Flutter imports (D-08, enforced by tools/check-domain-purity.sh).

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hugrun/core/alphabet/alphabet.dart';
import 'package:hugrun/core/alphabet/icelandic_letter.dart';
import 'package:hugrun/core/tracing/glyph_loader.dart';

const Set<String> _diacriticSlugs = <String>{
  'a_acute',
  'e_acute',
  'i_acute',
  'o_acute',
  'u_acute',
  'y_acute',
  'o_umlaut',
};

const Set<String> _twoPartIcelandicSlugs = <String>{'eth', 'thorn'};

void main() {
  group('assetPathFor', () {
    test('canonical path for "a" → assets/tracing/a.json', () {
      final letter = kIcelandicAlphabet.first;
      expect(letter.assetSlug, 'a');
      expect(assetPathFor(letter), 'assets/tracing/a.json');
    });

    test('canonical path for "ð" → assets/tracing/eth.json', () {
      final letter = kIcelandicAlphabet.firstWhere((l) => l.glyph == 'ð');
      expect(assetPathFor(letter), 'assets/tracing/eth.json');
    });

    test('canonical path for "ö" → assets/tracing/o_umlaut.json', () {
      final letter = kIcelandicAlphabet.firstWhere((l) => l.glyph == 'ö');
      expect(assetPathFor(letter), 'assets/tracing/o_umlaut.json');
    });
  });

  group('parseGlyphJson', () {
    test('parses a valid 1-stroke glyph and returns a TraceGlyph', () {
      const raw = '{"character":"l",'
          '"strokes":["M 0 0 L 100 0 L 100 100 L 0 100 Z"],'
          '"medians":[[[50,0],[50,100]]],'
          '"radStrokes":[]}';
      final glyph = parseGlyphJson(raw);
      expect(glyph.character, 'l');
      expect(glyph.strokes.length, 1);
      expect(glyph.medians.length, 1);
      expect(glyph.radStrokes, isEmpty);
    });

    test('throws FormatException on missing strokes', () {
      const raw = '{"character":"x","medians":[[[0,0],[1,1]]]}';
      expect(() => parseGlyphJson(raw), throwsFormatException);
    });

    test('throws FormatException on stroke/median count mismatch', () {
      const raw = '{"character":"x",'
          '"strokes":["M 0 0 L 1 1 Z","M 0 0 L 2 2 Z"],'
          '"medians":[[[0,0],[1,1]]]}';
      expect(() => parseGlyphJson(raw), throwsFormatException);
    });

    test('throws FormatException on empty strokes list', () {
      const raw = '{"character":"x","strokes":[],"medians":[]}';
      expect(() => parseGlyphJson(raw), throwsFormatException);
    });

    test('preserves diacritic glyphs (e.g. á)', () {
      const raw = '{"character":"á",'
          '"strokes":["M 0 0 L 1 1 Z","M 0 0 L 2 2 Z"],'
          '"medians":[[[0,0],[100,100]],[[200,800],[300,850]]],'
          '"radStrokes":[]}';
      final glyph = parseGlyphJson(raw);
      expect(glyph.character, 'á');
      expect(glyph.strokes.length, 2);
    });
  });

  group('shipped 32 glyphs at assets/tracing/', () {
    // The shipped files are generated by tools/glyph/generate_simple_traces.py.
    // Tests load via dart:io to bypass the rootBundle (these are
    // pure-Dart tests, no widget binding).

    Map<String, TraceGlyph> loadAllShippedGlyphs() {
      final root = Directory.current;
      final result = <String, TraceGlyph>{};
      for (final letter in kIcelandicAlphabet) {
        final path = '${root.path}/assets/tracing/${letter.assetSlug}.json';
        final file = File(path);
        if (!file.existsSync()) {
          fail('Missing glyph file: $path');
        }
        final raw = file.readAsStringSync();
        try {
          result[letter.assetSlug] = parseGlyphJson(raw);
        } catch (e) {
          fail('Failed to parse $path: $e');
        }
      }
      return result;
    }

    test('all 32 alphabet slugs have a JSON file under assets/tracing/', () {
      for (final letter in kIcelandicAlphabet) {
        final path = 'assets/tracing/${letter.assetSlug}.json';
        expect(
          File(path).existsSync(),
          isTrue,
          reason: 'Missing $path for ${letter.glyph}',
        );
      }
    });

    test('all 32 glyphs parse via parseGlyphJson without throwing', () {
      final glyphs = loadAllShippedGlyphs();
      expect(glyphs.length, 32);
    });

    test('every glyph has ≥1 stroke and stroke count == median count', () {
      final glyphs = loadAllShippedGlyphs();
      for (final entry in glyphs.entries) {
        final g = entry.value;
        expect(g.strokes.length, greaterThanOrEqualTo(1),
            reason: '${entry.key} has 0 strokes');
        expect(g.strokes.length, g.medians.length,
            reason: '${entry.key} stroke/median count mismatch');
      }
    });

    test('every median has ≥2 points', () {
      final glyphs = loadAllShippedGlyphs();
      for (final entry in glyphs.entries) {
        for (var i = 0; i < entry.value.medians.length; i++) {
          expect(
            entry.value.medians[i].length,
            greaterThanOrEqualTo(2),
            reason: '${entry.key} stroke $i has <2 median points',
          );
        }
      }
    });

    test('Pitfall §2 — diacritic letters have ≥2 strokes and accent is LAST',
        () {
      final glyphs = loadAllShippedGlyphs();
      for (final slug in _diacriticSlugs) {
        final g = glyphs[slug]!;
        expect(g.strokes.length, greaterThanOrEqualTo(2),
            reason: '$slug should have ≥2 strokes (body + accent)');
        // The accent is the LAST stroke; its median should be entirely
        // ABOVE (= higher Y in MMAH document space — i.e. greater y) the
        // body strokes' medians.
        final lastMedian = g.medians.last;
        final lastMinY = lastMedian
            .map((p) => p[1])
            .reduce((a, b) => a < b ? a : b);
        for (var i = 0; i < g.medians.length - 1; i++) {
          final priorMedian = g.medians[i];
          final priorMaxY = priorMedian
              .map((p) => p[1])
              .reduce((a, b) => a > b ? a : b);
          expect(
            lastMinY,
            greaterThanOrEqualTo(priorMaxY),
            reason: '$slug: accent stroke (last) should be above '
                'prior stroke $i in MMAH Y (y-up)',
          );
        }
      }
    });

    test('Icelandic-specific ð has exactly 2 strokes (body + cross-bar)', () {
      final g = loadAllShippedGlyphs()['eth']!;
      expect(g.strokes.length, 2);
    });

    test('Icelandic-specific þ has exactly 2 strokes (spine + bowl)', () {
      final g = loadAllShippedGlyphs()['thorn']!;
      expect(g.strokes.length, 2);
    });

    test(
      'every shipped JSON is valid MMAH (json structure check)',
      () {
        for (final letter in kIcelandicAlphabet) {
          final path = 'assets/tracing/${letter.assetSlug}.json';
          final raw = File(path).readAsStringSync();
          final decoded = jsonDecode(raw) as Map<String, dynamic>;
          expect(decoded.containsKey('character'), isTrue,
              reason: '$path missing "character"');
          expect(decoded.containsKey('strokes'), isTrue,
              reason: '$path missing "strokes"');
          expect(decoded.containsKey('medians'), isTrue,
              reason: '$path missing "medians"');
        }
      },
    );

    test('two-part Icelandic letters (ð, þ) and diacritics are accounted for',
        () {
      // Sanity check on the two manifest sets at the top of this file.
      for (final s in _diacriticSlugs.followedBy(_twoPartIcelandicSlugs)) {
        expect(
          kIcelandicAlphabet.where((l) => l.assetSlug == s),
          isNotEmpty,
          reason: '$s not in kIcelandicAlphabet',
        );
      }
    });
  });
}

extension<T> on Iterable<T> {
  Iterable<T> followedBy(Iterable<T> other) sync* {
    yield* this;
    yield* other;
  }
}
