#!/usr/bin/env python3
"""Corpus-level distributions and outlier identification.

Reads audio-review/clip_stats.json and writes:
  - audio-review/histograms/rms.png
  - audio-review/histograms/peak.png
  - audio-review/histograms/duration.png
  - audio-review/histograms/centroid.png
  - audio-review/corpus-summary.md (human-readable)
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
STATS_PATH = REPO_ROOT / "audio-review" / "clip_stats.json"
HIST_DIR = REPO_ROOT / "audio-review" / "histograms"
SUMMARY = REPO_ROOT / "audio-review" / "corpus-summary.md"


def hist(values, title: str, xlabel: str, out_path: Path, bins: int = 20,
         color: str = "#1565C0") -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5), dpi=100)
    ax.hist(values, bins=bins, color=color, edgecolor="white", linewidth=0.5)
    mean = float(np.mean(values))
    std = float(np.std(values))
    ax.axvline(mean, color="red", linewidth=1, label=f"mean={mean:.2f}")
    ax.axvline(mean + std, color="orange", linewidth=0.8, linestyle="--",
               label=f"±1σ ({std:.2f})")
    ax.axvline(mean - std, color="orange", linewidth=0.8, linestyle="--")
    ax.set_title(title, fontsize=10)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("count")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3, linewidth=0.4)
    fig.tight_layout()
    fig.savefig(out_path, dpi=100)
    plt.close(fig)


def main() -> int:
    HIST_DIR.mkdir(parents=True, exist_ok=True)
    payload = json.loads(STATS_PATH.read_text())
    clips = [c for c in payload["clips"] if c["file_exists"] and not c["error"]]
    if not clips:
        print("no valid clips to summarize", flush=True)
        return 1

    rms = [c["rms_db"] for c in clips]
    peak = [c["peak_db"] for c in clips]
    dur = [c["duration_s"] for c in clips]
    cent = [c["spectral_centroid_mean_hz"] for c in clips]
    lead = [c["leading_silence_ms"] for c in clips]
    trail = [c["trailing_silence_ms"] for c in clips]

    hist(rms, "RMS distribution (dBFS)", "RMS dBFS", HIST_DIR / "rms.png")
    hist(peak, "Peak distribution (dBFS)", "Peak dBFS", HIST_DIR / "peak.png", color="#C62828")
    hist(dur, "Duration distribution (s)", "Duration (s)", HIST_DIR / "duration.png", color="#2E7D32")
    hist(cent, "Spectral centroid distribution (Hz)", "Centroid (Hz)",
         HIST_DIR / "centroid.png", color="#6A1B9A")

    # Outliers per dimension
    def extremes(values, keys, label_fmt):
        idx_min = int(np.argmin(values))
        idx_max = int(np.argmax(values))
        return {
            "min": {"key": keys[idx_min], "value": values[idx_min],
                    "label": label_fmt.format(v=values[idx_min])},
            "max": {"key": keys[idx_max], "value": values[idx_max],
                    "label": label_fmt.format(v=values[idx_max])},
        }

    keys = [c["key"] for c in clips]
    outliers = {
        "rms_db": extremes(rms, keys, "{v:.2f} dBFS"),
        "peak_db": extremes(peak, keys, "{v:.2f} dBFS"),
        "duration_s": extremes(dur, keys, "{v:.3f} s"),
        "spectral_centroid_hz": extremes(cent, keys, "{v:.0f} Hz"),
        "leading_silence_ms": extremes(lead, keys, "{v:.1f} ms"),
        "trailing_silence_ms": extremes(trail, keys, "{v:.1f} ms"),
    }

    rms_mean = statistics.fmean(rms)
    rms_std = statistics.pstdev(rms) if len(rms) > 1 else 0.0

    # Build "must look at" list = the per-dimension extreme keys (deduped)
    must_look = []
    seen = set()
    for dim, ends in outliers.items():
        for endpoint in ("min", "max"):
            k = ends[endpoint]["key"]
            if k not in seen:
                seen.add(k)
                must_look.append({
                    "key": k,
                    "reason": f"{dim} {endpoint}",
                    "value": ends[endpoint]["label"],
                })

    lines = []
    lines.append("# Hugrún corpus acoustic summary\n")
    lines.append("Auto-generated by `tools/audio_review/compare_corpus.py`. ")
    lines.append("Acoustic statistics only — does NOT validate Icelandic pronunciation.\n\n")
    lines.append(f"- Voice: `{payload.get('voice')}`\n")
    lines.append(f"- Total clips analyzed: **{len(clips)}**\n")
    lines.append(f"- RMS: mean **{rms_mean:.2f} dBFS**, std **{rms_std:.2f} dB**\n")
    lines.append(f"- Peak: mean **{np.mean(peak):.2f} dBFS**, max **{np.max(peak):.2f} dBFS**\n")
    lines.append(f"- Duration: min **{np.min(dur):.3f} s**, ")
    lines.append(f"max **{np.max(dur):.3f} s**, mean **{np.mean(dur):.3f} s**\n")
    lines.append(f"- Spectral centroid: mean **{np.mean(cent):.0f} Hz**, "
                 f"range [{np.min(cent):.0f}, {np.max(cent):.0f}] Hz\n\n")

    lines.append("## Histograms\n")
    lines.append("- ![RMS](histograms/rms.png)\n")
    lines.append("- ![Peak](histograms/peak.png)\n")
    lines.append("- ![Duration](histograms/duration.png)\n")
    lines.append("- ![Centroid](histograms/centroid.png)\n\n")

    lines.append("## Per-dimension extremes\n\n")
    lines.append("| Dimension | Min (key / value) | Max (key / value) |\n")
    lines.append("| --- | --- | --- |\n")
    for dim, ends in outliers.items():
        lines.append(f"| `{dim}` | `{ends['min']['key']}` / {ends['min']['label']} "
                     f"| `{ends['max']['key']}` / {ends['max']['label']} |\n")
    lines.append("\n")

    lines.append("## Must-look-at clips (per-dimension extremes, deduped)\n\n")
    lines.append("Open these spectrograms with the `Read` tool to visually verify:\n\n")
    for entry in must_look:
        spec_path = REPO_ROOT / "audio-review" / "spectrograms" / f"{entry['key']}.png"
        rel = spec_path.relative_to(REPO_ROOT)
        lines.append(f"- `{entry['key']}` — *{entry['reason']}* ({entry['value']}) → "
                     f"`{rel}`\n")
    lines.append("\n")

    SUMMARY.write_text("".join(lines))
    print(f"Wrote {SUMMARY.relative_to(REPO_ROOT)}")
    print(f"Wrote 4 histograms under {HIST_DIR.relative_to(REPO_ROOT)}/")

    # Write outliers JSON sidecar (machine-readable)
    (REPO_ROOT / "audio-review" / "outliers.json").write_text(
        json.dumps({"per_dimension": outliers, "must_look": must_look},
                   indent=2, ensure_ascii=False)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
