// Phase 10 Plan 01 — Drift v1 → v2 schema migration test (RED first).
//
// Verifies Phase 10 D-01..D-04:
//   * v2 adds `photo_tags` and `activity_log` tables, both empty after migrate.
//   * `child_profiles` from v1 is preserved (data + structure) — D-04.
//   * Migration is non-destructive: no v1 table dropped or modified.
//   * Schema verifier round-trips v1 → v2 with no validation errors.
//
// Uses drift_dev's `SchemaVerifier` with the schemaAt(1) snapshot committed in
// Phase 1 Plan 02. A v2 snapshot will be added in this plan and the v2 verifier
// helper auto-regenerated by `dart run drift_dev schema generate`.
import 'package:drift/native.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hugrun/core/db/database.dart';

import '../generated/schema.dart';
import '../generated/schema_v1.dart' as v1;

void main() {
  late SchemaVerifier verifier;
  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  test(
    'migrates v1 → v2: child_profiles row preserved through upgrade',
    () async {
      final schema = await verifier.schemaAt(1);

      // 1. Populate v1 via raw SQL (v1 schema snapshot is TableInfo-only;
      //    no Companion classes generated for snapshot helpers).
      final v1Db = v1.DatabaseAtV1(schema.newConnection());
      await v1Db.customStatement(
        "INSERT INTO child_profiles(name, created_at) "
        "VALUES('Hugrún', 1700000000)",
      );
      await v1Db.close();

      // 2. Run the v1 → v2 migration via the production AppDatabase migration
      //    strategy.
      final db = AppDatabase.forTesting(schema.newConnection());
      await verifier.migrateAndValidate(db, 2);
      addTearDown(db.close);

      // 3. Assert child_profiles row preserved (D-04).
      final preserved = await db.childProfilesDao.readLatest();
      expect(preserved, isA<Object>());
      expect(preserved!.name, 'Hugrún');

      // 4. Assert v2 tables exist and are empty.
      final tables = await db
          .customSelect(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "ORDER BY name",
          )
          .get();
      final names = tables.map((r) => r.read<String>('name')).toList();
      expect(names, contains('child_profiles'));
      expect(names, contains('photo_tags'));
      expect(names, contains('activity_log'));

      final photoCount = await db
          .customSelect('SELECT COUNT(*) AS n FROM photo_tags')
          .map((r) => r.read<int>('n'))
          .getSingle();
      expect(photoCount, 0);

      final logCount = await db
          .customSelect('SELECT COUNT(*) AS n FROM activity_log')
          .map((r) => r.read<int>('n'))
          .getSingle();
      expect(logCount, 0);
    },
  );

  test('v2 photo_tags accepts insert + readback after migration', () async {
    final schema = await verifier.schemaAt(1);
    final db = AppDatabase.forTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 2);
    addTearDown(db.close);

    // Insert a row using raw SQL — DAO is added in Workstream C.
    await db.customStatement(
      "INSERT INTO photo_tags(image_path, lexicon_word, created_at) "
      "VALUES('/tmp/abc.jpg', 'hundur', 1700000000000)",
    );

    final rows = await db
        .customSelect('SELECT image_path, lexicon_word FROM photo_tags')
        .get();
    expect(rows, hasLength(1));
    expect(rows.first.read<String>('image_path'), '/tmp/abc.jpg');
    expect(rows.first.read<String>('lexicon_word'), 'hundur');
  });

  test('schemaVersion is 2', () {
    final db = AppDatabase.forTesting(NativeDatabase.memory());
    addTearDown(db.close);
    expect(db.schemaVersion, 2);
  });
}
